### ISSUE TITLE
Implementation not found

### ISSUE THREAD

**Issue by PemmasaniRajesh** [glcas/faceDemo#2]
I'm getting this error when I tried to implement the face recognition in my application. I'm using product flavours in my app. Any insight on this would be appreciated.

![image](https://user-images.githubusercontent.com/10286949/94925165-693f3b80-04dc-11eb-860c-e5e73cd89233.png)

For you reference, I've attached my class above.

**Comment by glcas** [comment]
In my project, all method in class Face is implemented in cpp/face_jni.cpp, since the implementation of face recognition is written by c++.
Did you include the c++ files to your application?

**Comment by PemmasaniRajesh** [comment]
Yeah it's included. I understand like it will autogenerate if we build the project. I found that these methods has to be linked to the classes in c++. How to change the packagename in c++ ? Can we change it manually or we can change it in one place ?

**Comment by glcas** [comment]
You can declare a namespace in c++ like `using namespace Face1;`, which has the same name as the Java class. Then you should make sure the functions in c++ jni file has the format like `Java_packagename_methodname`.
By the way, I also found there are some tools to generate interface file from java to c++. But if you don't want to implement face recognition again, maybe just modifying the original code is enough.

**Comment by PemmasaniRajesh** [comment]
Thank you
