### ISSUE TITLE
Any Wiki about the project in pipeline ?

### ISSUE THREAD

**Issue by PemmasaniRajesh** [glcas/faceDemo#3]
I can see you've hardcoded the preview width and height. But I'm using width: match_parent, height:match_parent for my preview. 

So when I try to draw the bounding box, it's not coming properly.

Can you tell me how to draw the bounding box on face over width: match_parent, height:match_parent ?

**Comment by glcas** [comment]
You can get the size of your preview and set the same size for analyzer (see [setTargetResolution](https://developer.android.com/reference/androidx/camera/core/ImageAnalysis.Builder#setTargetResolution(android.util.Size))).
Note that the maximum available resolution that could be selected for an ImageAnalysis is limited to be under 1080p. So if your preview size is lager than 1080 pixels, you have to set the size for analyzer smaller and in proportion to the preview size.
Then the preview is flipped horizontally. You should draw boxes with horizontal flip (and ratio possibly).
At last, I'm afraid I have no time to write a detailed wiki. I will answer the questions if available.

**Comment by PemmasaniRajesh** [comment]
I've understood the analyzer part. So I undetstood the value 480 in the code below is half of the preview width?

`                    canvas.drawRect((480 - boxes.get(i)[0]) * 2, boxes.get(i)[1] * 2, (480 - boxes.get(i)[2]) * 2, boxes.get(i)[3] * 2, paint);
`
Here is the preview code below:

`<androidx.camera.view.PreviewView
            android:id="@+id/preview_view"
            android:layout_width="960px"
            android:layout_height="1280px">
 </androidx.camera.view.PreviewView>`

The bounding box is formatted as [x, y, width, height] under the key 'box'. Reference: https://github.com/ipazc/mtcnn

Is this what we're getting ?

**Comment by glcas** [comment]
Yes, that's right.
The only difference is that the box we got is formatted as [left, top, right, bottom].

**Comment by PemmasaniRajesh** [comment]
If we're getting this format [left, top, right, bottom], can you explain me why you're subtracting the coordinates from 480 and multiplying the coordinates*2 ?

**Comment by glcas** [comment]
Subtraction for horizontal flip and multiplying because I got the box from 480\*640 images while my preview is 960\*1280.

**Comment by PemmasaniRajesh** [comment]
Got that. Thanks a lot
