### ISSUE TITLE
Accuracy issues in low lighting and high lighting

### ISSUE THREAD

**Issue by PemmasaniRajesh** [glcas/faceDemo#5]
I've implemented the face recognition in other application where I'm using Euclidean method to calculate the distance between the vectors. I've kept a threshold of 0.7. 

It's working fine and giving good results when we try to recognize the face in the same place where we registered the face. Accuracy is between 0.3 to o.6.

But If we change the place where low lighting/high lighting is there accuracy is between 0.6 to 0.8. Is there anyway to get good accuracy level between 0.3 to 0.6 ?

Is this library doing face alignment also like Affine transformation ?

**Comment by glcas** [comment]
If you're using Euclidean distance, the suggested range of threshold is 0.8~1.4 (deepinsight/insightface#168).

I've used alignment while the commented out code only does scaling transformation.

```cpp
    ncnn::Mat det1 = mRecognize->preprocess(ncnn_img1, mtcnnLandmarks1);
    // ncnn::Mat det1 = ncnn::Mat::from_pixels_resize(faceImageCharDate1, ncnn::Mat::PIXEL_RGBA2RGB, w1, h1,112,112);
```

The code is in the implementation of method `FaceRecognize`.

**Comment by PemmasaniRajesh** [comment]
Okie, so the lesser the better right. I mean we've to take the face which is giving lesser distance.

Also, which one you'll suggest to get good results between Cosnine Similarity and Euclidean distance ?

**Comment by glcas** [comment]
I think Cosine Similarity is better.

**Comment by PemmasaniRajesh** [comment]
Can you tell me For Cosnine Similarity what's the threshold I've to use in all lighting conditions ?

**Comment by glcas** [comment]
In my tests 0.5 is a good choice.

**Comment by rsingh2083** [comment]
@PemmasaniRajesh  how did you build this app, Im getting this error :- https://github.com/glcas/faceDemo/issues/7
